export const HOST = `http://localhost:4000`
export const id_home=''
export const GET_TEMPERATURE_REQ = "GET_TEMPERATURE_REQ"
export const GET_TEMPERATURE_SUCCESS = "GET_TEMPERATURE_SUCCESS"
export const GET_TEMPERATURE_FAIL = "GET_TEMPERATURE_FAIL"

export const ADD_STATELED_REQ = "ADD_STATELED_REQ"
export const ADD_STATELED_SUCCESS = "ADD_STATELED_SUCCESS"
export const ADD_STATELED_FAIL = "ADD_STATELED_FAIL"

export const ADD_STATEDOOR_REQ = "ADD_STATEDOOR_REQ"
export const ADD_STATEDOOR_SUCCESS = "ADD_STATEDOOR_SUCCESS"
export const ADD_STATEDOOR_FAIL = "ADD_STATEDOOR_FAIL"

export const UPDATE_AIR_REQ = "UPDATE_AIR_REQ"
export const UPDATE_AIR_SUCCESS = "UPDATE_AIR_SUCCESS"
export const UPDATE_AIR_FAIL = "UPDATE_AIR_FAIL"

export const LOGIN_REQ = "LOGIN_REQ"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const REGISTER_REQ = "REGISTER_REQ"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const GET_USER_REQ = 'GET_USER_REQ'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAIL = 'GET_USER_FAIL'

export const ADD_HOME_REQ = 'ADD_HOME_REQ'
export const ADD_HOME_SUCCESS = 'ADD_HOME_SUCCESS'
export const ADD_HOME_FAIL = 'ADD_HOME_FAIL'

export const DELETE_HOME_REQ = 'DELETE_HOME_REQ'
export const DELETE_HOME_SUCCESS = 'DELETE_HOME_SUCCESS'
export const DELETE_HOME_FAIL = 'DELETE_HOME_FAIL'
